comment: |md
## Big Bang Deployment Flow
See [Description](./DESCRIPTION.md) for details on the flow
  
|


# Git Repository Components (repo1)
gitrepo: {
  label: Git Code Repository
  style: {
    fill: '#acd7e1'
    stroke-width: 5
    font-size: 20
  }
  cust-repo: {
    label: "Customer Repo"
    style: {
      fill: '#e1d7ac'
      font-size: 20
    }
    cust-env: {
      label: "Customer Environment"
      shape: image
      icon: images/git-folder.svg
      width: 200
      height: 200
      font-size: 10
      link: 'https://raw.githubusercontent.com/MxNxPx/diagram-as-code/main/customer-bigbang.svg?sanitize=true'
    }
  } 

  bb-repo: {
    label: "Big Bang Repo"
    style: {
      fill: '#e1d7ac'
      font-size: 20
    }
    bb-umb: {
      label: "Big Bang Umbrella"
      shape: image
      icon: images/git-folder.svg
      width: 200
      height: 200
      font-size: 10
    }
  } 

  ms-repo: {
    label: "Metrics-Server Chart Repo"
    style: {
      fill: '#e1d7ac'
      font-size: 20
    }
    ms-chart {
      shape: image
      icon: images/git-folder.svg
      width: 200
      height: 200
      font-size: 10
    }
  } 

}

# Kubernetes Cluster Components
k8s: {
  label: K8s Cluster
  style: {
    fill: '#acd7e1'
    stroke-width: 5
    font-size: 20
  }
  flux: {
    label: Flux Components
    style: {
      fill: '#e1d7ac'
      font-size: 20
    }
    ks-cr: {
      label: Kustomization CRs
      style: {
        fill: '#ace1ac'
        font-size: 20
      }
      cust-bb-ks-cr: {
        label: Customer Big Bang Kustomization CR
        shape: image
        icon: images/flux-kustomization-logo.svg
        width: 200
        height: 200
        font-size: 10 
      }
    }
    hr-cr: {
      label: HelmRelease CRs
      style: {
        fill: '#ace1ac'
        font-size: 20
      }
      bb-hr-cr: {
        label: Big Bang HelmRelease CR
        shape: image
        icon: images/flux-helmrelease-logo.svg
        width: 200
        height: 200
        font-size: 10 
      }
      ms-hr-cr: {
        label: Metrics-Server HelmRelease CR
        shape: image
        icon: images/flux-helmrelease-logo.svg
        width: 200
        height: 200
        font-size: 10 
      }
    }
    hc-cr: {
      label: HelmChart CRs
      style: {
        fill: '#ace1ac'
        font-size: 20
      }
      ms-hc-cr: {
        label: Metrics-Server HelmChart CR
        shape: image
        icon: images/flux-helmchart-logo.svg
        width: 200
        height: 200
        font-size: 10 
      }
    }
    gr-cr: {
      label: GitRepository CRs
      style: {
        fill: '#ace1ac'
        font-size: 20
      }
      cust-bb-gr-cr: {
        label: Customer Big Bang GitRepository CR
        shape: image
        icon: images/flux-gitrepo-logo.svg
        width: 200
        height: 200
        font-size: 10 
      }
      bb-gr-cr: {
        label: Big Bang GitRepository CR
        shape: image
        icon: images/flux-gitrepo-logo.svg
        width: 200
        height: 200
        font-size: 10 
      }
      ms-gr-cr: {
        label: Metrics-Server GitRepository CR
        shape: image
        icon: images/flux-gitrepo-logo.svg
        width: 200
        height: 200
        font-size: 10 
      }
    }
  }
  helm: {
    label: Helm Releases
    style: {
      fill: '#e1d7ac'
      font-size: 20
    }
    bb-hr: {
      label: Big Bang Helm Release
      shape: image
      icon: images/helm-release-logo.svg
      width: 200
      height: 200
      font-size: 10 
    }
    ms-hr: {
      label: Metrics-Server Helm Release
      shape: image
      icon: images/helm-release-logo.svg
      width: 200
      height: 200
      font-size: 10 
    }
  }
  ns: {
    label: Namespaces
    style: {
      fill: '#e1d7ac'
      font-size: 20
    }
    ms-ns: {
      label: Metrics-Server Namespace
      style: {
        fill: '#ace1ac'
        font-size: 20
      }
      ms-pods: {
        label: Metrics-Server Pods
        shape: image
        icon: images/pod.svg
        font-size: 10 
      }
      ms-svcs: {
        label: Metrics-Server Services
        shape: image
        icon: images/svc.svg
        font-size: 10
      }
      ms-cms: {
        label: Metrics-Server Configmaps
        shape: image
        icon: images/cm.svg
        font-size: 10
      }
    }
  }
}

# Container Registry Components (registry11)
registry: {
  label: Container Registry
  style: {
    fill: '#acd7e1'
    stroke-width: 5
    font-size: 20
  }
  ms-image: {
    label: kubernetes-sigs/metrics-server:0.6.2
    shape: image
    icon: images/container-logo.svg
    width: 200
    height: 200
    font-size: 10
  }
}


# Arrows describing relationships
gitrepo.cust-repo.cust-env -> k8s.flux.hr-cr.bb-hr-cr: '[1b]' #creates bb flux hr cr
gitrepo.cust-repo.cust-env -> k8s.flux.gr-cr.bb-gr-cr: '[1c]' #creates bb flux gr cr
k8s.flux.hr-cr.bb-hr-cr <-> k8s.flux.gr-cr.bb-gr-cr: '[1d]' #bb hr cr uses bb gr cr as source
k8s.flux.gr-cr.bb-gr-cr <-> gitrepo.bb-repo.bb-umb: '[1e]' #sync of the bb gr cr with the bb repo
gitrepo.cust-repo.cust-env -> k8s.flux.ks-cr.cust-bb-ks-cr: '[2a]' #creates the cust bb ks cr
gitrepo.cust-repo.cust-env -> k8s.flux.gr-cr.cust-bb-gr-cr: '[2b]' #creates the cust bb gr cr
k8s.flux.ks-cr.cust-bb-ks-cr <-> k8s.flux.gr-cr.cust-bb-gr-cr: '[2c]' #cust bb ks cr uses cust bb gr cr as source
k8s.flux.gr-cr.cust-bb-gr-cr <-> gitrepo.cust-repo.cust-env: '[2d]' #sync of the cust bb gr cr with the cust repo
k8s.flux.hr-cr.bb-hr-cr -> k8s.helm.bb-hr: '[3]'
k8s.helm.bb-hr -> k8s.flux.hr-cr.ms-hr-cr: '[4a]' #creates flux logging hr cr
k8s.helm.bb-hr -> k8s.flux.gr-cr.ms-gr-cr: '[4b]' #creates flux logging gitrepo cr
k8s.flux.gr-cr.ms-gr-cr <-> gitrepo.ms-repo.ms-chart: '[4c]' #reconciles repo
k8s.flux.hr-cr.ms-hr-cr <-> k8s.flux.gr-cr.ms-gr-cr: '[4d]' #logging hr cr uses logging gr cr as source
k8s.flux.hr-cr.ms-hr-cr -> k8s.flux.hc-cr.ms-hc-cr: '[4e]' #creates flux logging hc cr
k8s.flux.hr-cr.ms-hr-cr -> k8s.helm.ms-hr: '[5]' #creates logging helm release
k8s.helm.ms-hr -> k8s.ns.ms-ns.ms-pods: '[6]' #creates pods
k8s.helm.ms-hr -> k8s.ns.ms-ns.ms-svcs: '[6]' #creates services
k8s.helm.ms-hr -> k8s.ns.ms-ns.ms-cms: '[6]' #creates configmaps
k8s.ns.ms-ns.ms-pods -> registry.ms-image: '[7]' #pulls elastic image
