comment: |md
## Customer Big Bang Deployment Flow
See [Description](https://github.com/MxNxPx/diagram-as-code/blob/main/DESCRIPTION.md) for details on the flow
 
|


# Git Repository Components (repo1)
gitrepo: {
  label: Git Code Repository
  style: {
    fill: '#acd7e1'
    stroke-width: 5
    font-size: 20
  }
  cust-repo: {
    label: "Customer Repo"
    style: {
      fill: '#e1d7ac'
      font-size: 20
    }
    cust-env: {
      label: "Customer Environment"
      style: {
        fill: '#e1d7ac'
        font-size: 20
      }
      kust-over: {
        label: "Kustomize Overlays (per env)"
        style: {
          fill: '#e1d7ac'
          font-size: 20
        }
          bb-gr-cr: {
            label: "Big Bang Flux GitRepository CR"
            shape: image
            icon: images/git-folder.svg
            width: 200
            height: 200
            font-size: 10
            link: 'https://repo1.dso.mil/platform-one/big-bang/customers/template/-/blob/main/dev/kustomization.yaml'
           }
          bb-hr-cr: {
            label: "Big Bang Flux HelmRelease CR"
            shape: image
            icon: images/git-folder.svg
            width: 200
            height: 200
            font-size: 10
            link: 'https://repo1.dso.mil/platform-one/big-bang/customers/template/-/blob/main/dev/kustomization.yaml'
          }
      }
      cust-bb-gr-cr: {
        label: "Customer Big Bang Flux GitRepository CR"
        shape: image
        icon: images/git-folder.svg
        width: 200
        height: 200
        font-size: 10
        link: 'https://repo1.dso.mil/platform-one/big-bang/customers/template/-/blob/main/dev/bigbang.yaml'
      }
      cust-bb-ks-cr: {
        label: "Customer Big Bang Flux Kustomization CR"
        shape: image
        icon: images/git-folder.svg
        width: 200
        height: 200
        font-size: 10
        link: 'https://repo1.dso.mil/platform-one/big-bang/customers/template/-/blob/main/dev/bigbang.yaml'
      }
      kust-result: {
        label: "Kustomize Results (not a real repo)"
        style: {
          fill: '#a89732'
          font-size: 20
        }
        bb-gr-cr: {
          label: "Kustomize Big Bang Flux GitRepository CR"
          shape: image
          icon: images/git-kustomize-folder.svg
          width: 200
          height: 200
          font-size: 10
        }
        bb-hr-cr: {
          label: "Kustomize Big Bang Flux HelmRelease CR"
          shape: image
          icon: images/git-kustomize-folder.svg
          width: 200
          height: 200
          font-size: 10
        }
      }
    }
  } 

  bb-repo: {
    label: "Big Bang Repo"
    style: {
      fill: '#e1d7ac'
      font-size: 20
    }
    kust-base: {
      label: "Kustomize Base"
      style: {
        fill: '#e1d7ac'
        font-size: 20
      }
      bb-gr-cr: {
        label: "Big Bang Flux GitRepository CR"
        shape: image
        icon: images/git-folder.svg
        width: 200
        height: 200
        font-size: 10
        link: 'https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/base/gitrepository.yaml'
      }
      bb-hr-cr: {
        label: "Big Bang Flux HelmRelease CR"
        shape: image
        icon: images/git-folder.svg
        width: 200
        height: 200
        font-size: 10
        link: 'https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/base/helmrelease.yaml'
      }
    }
    bb-umb: {
      label: "Big Bang Umbrella"
      style: {
        fill: '#e1d7ac'
        font-size: 20
      }
      bb-ms-gr-cr: {
        label: "Big Bang Metrics-Server GitRepository CR"
        shape: image
        icon: images/git-folder.svg
        width: 200
        height: 200
        font-size: 10
        link: 'https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/chart/templates/metrics-server/gitrepository.yaml'
      }
      bb-ms-hr-cr: {
        label: "Big Bang Metrics-Server HelmRelease CR"
        shape: image
        icon: images/git-folder.svg
        width: 200
        height: 200
        font-size: 10
        link: 'https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/chart/templates/metrics-server/helmrelease.yaml'
      }
    }
  } 

  ms-repo: {
    label: "Metrics-Server Chart Repo"
    style: {
      fill: '#e1d7ac'
      font-size: 20
    }
    ms-chart {
      label: "Metrics-Server Chart"
      shape: image
      icon: images/git-folder.svg
      width: 200
      height: 200
      font-size: 10
      link: 'https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/metrics-server/-/tree/main/chart'
    }
  } 
}

# Kubernetes Cluster Components
k8s: {
  label: K8s Cluster
  style: {
    fill: '#acd7e1'
    stroke-width: 5
    font-size: 20
  }
  bb-inst: {
    label: "Big Bang Instance"
    shape: image
    icon: images/flux-all-logo.svg
    width: 200
    height: 200
    font-size: 10
    link: 'https://htmlpreview.github.io/?https://github.com/MxNxPx/diagram-as-code/blob/main/bigbang-view.html'
   }
}



# Arrows describing relationships
gitrepo.bb-repo.kust-base.bb-gr-cr -> gitrepo.cust-repo.cust-env.kust-over.bb-gr-cr -> gitrepo.cust-repo.cust-env.kust-result.bb-gr-cr: '[1a]' #kustomize
gitrepo.bb-repo.kust-base.bb-hr-cr ->gitrepo.cust-repo.cust-env.kust-over.bb-hr-cr -> gitrepo.cust-repo.cust-env.kust-result.bb-hr-cr: '[1a]' #kustomize
gitrepo.cust-repo.cust-env.kust-result.bb-hr-cr -> k8s.bb-inst: '[1b]' #creates bb flux hr cr
gitrepo.cust-repo.cust-env.kust-result.bb-gr-cr -> k8s.bb-inst: '[1c]' #creates bb flux gr cr